define({
    selectFeatures: "Geometria",
    selectByAttribute: "Valor",
    results: "Resultados",
    searchLayer: "Buscar layer",
    searchType: "Buscar alias",
    selectFeaturesBy: "Seleccionar Featuares por",
    selectSpatial: "Espacial",
    search: "Buscar",
    clear: "Limpiar",
    clearBuffer: "Limpiar Buffer",
    zoomall: "Acercar a Todo",
    point: "Punto",
    line: "Linea",
    polyline: "Polilínea",
    freehandPolyline: "Polilínea Libre",
    triangle: "Triangulo",
    extent: "Extensión",
    circle: "Circulo",
    ellipse: "Elipse",
    polygon: "Polígono",
    freehandPolygon: "Polígono Libre",
    featuresSelected: "Elementos seleccionados: ",
    noResults: "Sin Resultados",
    searchError: "Busqueda Fallida !",
    searchResult: "Resultados de La Busqueda",
    useMultiGraphics: "Graficos Multiparte Habilitados",
    addTolerance: "Agregar Tolerancia de Busqueda a la selección por punto",
    specifyParamsTip: "Especifique los parámetros para esta Búsqueda",
    and: "Y",
    friendlyDatePattern: "MM/dd/yyyy",
    stringOperatorIs: 'stringOperatorIs',
    stringOperatorIsNot: 'stringOperatorIsNot',
    stringOperatorStartsWith: 'stringOperatorStartsWith',
    stringOperatorEndsWith: 'stringOperatorEndsWith',
    stringOperatorContains: 'stringOperatorContains',
    stringOperatorDoesNotContain: 'stringOperatorDoesNotContain',
    stringOperatorIsBlank: 'stringOperatorIsBlank',
    stringOperatorIsNotBlank: 'stringOperatorIsNotBlank',
    dateOperatorIsOn: 'dateOperatorIsOn',
    dateOperatorIsNotOn: 'dateOperatorIsNotOn',
    dateOperatorIsBefore: 'dateOperatorIsBefore',
    dateOperatorIsAfter: 'dateOperatorIsAfter',
    dateOperatorDays: 'dateOperatorDays',
    dateOperatorWeeks: 'dateOperatorWeeks',
    dateOperatorMonths: 'dateOperatorMonths',
    dateOperatorInTheLast: 'dateOperatorInTheLast',
    dateOperatorNotInTheLast: 'dateOperatorNotInTheLast',
    dateOperatorIsBetween: 'dateOperatorIsBetween',
    dateOperatorIsNotBetween: 'dateOperatorIsNotBetween',
    dateOperatorIsBlank: 'dateOperatorIsBlank',
    dateOperatorIsNotBlank: 'dateOperatorIsNotBlank',
    numberOperatorIs: 'numberOperatorIs',
    numberOperatorIsNot: 'numberOperatorIsNot',
    numberOperatorIsAtLeast: 'numberOperatorIsAtLeast',
    numberOperatorIsLessThan: 'numberOperatorIsLessThan',
    numberOperatorIsAtMost: 'numberOperatorIsAtMost',
    numberOperatorIsGreaterThan: 'numberOperatorIsGreaterThan',
    numberOperatorIsBetween: 'numberOperatorIsBetween',
    numberOperatorIsNotBetween: 'numberOperatorIsNotBetween',
    numberOperatorIsBlank: 'numberOperatorIsBlank',
    numberOperatorIsNotBlank: 'numberOperatorIsNotBlank',
    bufferGraphic: 'Buffer Gráfico',
    searchDistance: 'Aplicar Distancia de Búsqueda:',
    applyBuffer: 'Aplicar Buffer',
    searchEntities: 'Buscar Entidades de:',
    intersectMessage: 'No hay ningún resultado para intersectarse , por favor completar una búsqueda gráfica o de texto primero.',
    spatialSearchErrorTitle: 'Error en Busqueda Espacial',
    bufferMessage: 'No hay ningún resultado para el Buffer , por favor completar una búsqueda gráfica o de texto primero.',
    bufferSearchErrorTitle: 'Buffer error',
    spatialchoicemsg: '¿Quieres utilizar los gráficos de búfer o la selección de gráficos?',
    spatialchoicetitle: 'Escoger',
    buffergraphics: 'Búfer',
    selectiongraphics: 'Selección',
    widgetversion: 'eSearch Widget Version Info',
    widgetverstr: 'Widget Version',
    wabversionmsg: 'Widget is designed to run in Web AppBuilder version',
    exporturl: 'Exportar URL de Busqueda',
    copyurlprompt: 'Copiar al portapapeles: Ctrl+C, Enter',
    limit2mapextent: 'Limite la Busqueda a la extensión del mapa',
    graphicgeomtypemsg1: 'No se admite la combinación de  tipos de geometría como puntos, líneas y polígonos.',
    graphicgeomtypemsg2: '¿Quieres continuar con lo que resultará en la limpieza de todos los gráficos anteriores elaborados?',
    cancel: 'cancelar',
    _continue: 'continuar',
    warning: 'Advertencia!',
    zoomErrorMessage: 'Los intentos de zoom automático a los resultados de la búsqueda han fallado.',
    addTextQuery: 'Incluir consulta de texto en los criterios de selección',
    uniqueValues: 'Resiviendo valores únicos',
    processingUnique: 'Procesando valores únicos: ',
    of: ' de ',
    requiredTip: "El valor es requerido para ejecutar la búsqueda",
    required: "Requirido",
    requiredWarning: "Valor requerido no encontrado",
    requiredErrorMessage: "Usted no a ingresado uno o mas valores requeridos",
    selectFeaturesFrom: "Usar graficos desde",
    eLocateTip: "Use Existing Enhanced Locate Widget Graphics",
    createnewselection: "Crrear resultados nuevos",
    addtoselection: "Adicionar a los resultados actuales",
    removefromselection: "Removere de los resultados actuales",
    mapServiceFailureTitle: "Fallo en la busqueda de capa de servicio de mapas",
    mapServicefailureMsg: "The following search layer(s) map service(s) failed to respond: ",
    mapServicefailureMsg2: ". Due to this failure the search layer(s) will be removed from the widget.",
    removeResultMsg: "Remover resultados"
});
